spring:
  application:
    name: luxstore-api

  datasource:
    url: jdbc:postgresql://localhost:5432/luxstore
    username: postgres
    password: j2k@1Love

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: "luxstore-super-secret-key-change-this-to-a-long-random-key-123456789"
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  port: 8080